import Link from "next/link";
import Image from "next/image";
import {Megaphone} from "lucide-react";
import {prisma} from "@/lib/prisma";
import {AdImpressionPing} from "@/components/AdImpressionPing";

export async function AdSlot({compact=false,placement="HOME_BANNER"}:{compact?:boolean;placement?:"HOME_BANNER"|"SEARCH_INLINE"}){
  const now=new Date();
  const ad=await prisma.advertisement.findFirst({where:{status:"ACTIVE",placement:{in:[placement,"PREMIUM"]},AND:[{OR:[{startsAt:null},{startsAt:{lte:now}}]},{OR:[{endsAt:null},{endsAt:{gte:now}}]}]},orderBy:{updatedAt:"desc"}}).catch(()=>null);
  if(ad)return <section className={compact?"rounded-[1.5rem] border border-forest/10 bg-white p-5 shadow-soft":"bg-sand py-7"}><div className={compact?"":"shell"}><div className="flex flex-col gap-5 overflow-hidden rounded-[1.75rem] border border-forest/10 bg-white p-6 shadow-soft sm:flex-row sm:items-center sm:justify-between">{ad.imageUrl&&<div className="relative h-36 w-full overflow-hidden rounded-2xl sm:w-56"><Image src={ad.imageUrl} alt={ad.title} fill className="object-cover"/></div>}<div className="flex-1"><p className="text-xs font-extrabold uppercase tracking-[.18em] text-forest">Sponsorisé · {ad.advertiserName}</p><h2 className="mt-1 text-xl font-extrabold">{ad.title}</h2>{ad.description&&<p className="mt-1 max-w-2xl text-sm leading-6 text-ink/60">{ad.description}</p>}</div><Link href={`/api/ads/click?id=${encodeURIComponent(ad.id)}`} className="shrink-0 rounded-full bg-forest px-5 py-3 text-center text-sm font-bold text-white">Découvrir</Link><AdImpressionPing id={ad.id}/></div></div></section>;
  return <section className={compact?"rounded-[1.5rem] border border-forest/10 bg-white p-5 shadow-soft":"bg-sand py-7"}><div className={compact?"":"shell"}><div className="flex flex-col gap-5 rounded-[1.75rem] border border-forest/10 bg-white p-6 shadow-soft sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><div className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-lime text-ink"><Megaphone size={20}/></div><div><p className="text-xs font-extrabold uppercase tracking-[.18em] text-forest">Espace publicitaire</p><h2 className="mt-1 text-xl font-extrabold">Votre entreprise peut être visible ici</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-ink/60">Touchez directement les visiteurs de TOGOVEST.</p></div></div><Link href="/publicite" className="shrink-0 rounded-full bg-forest px-5 py-3 text-center text-sm font-bold text-white">Faire de la publicité</Link></div></div></section>;
}
